# Generated by Django 5.2.4 on 2025-09-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('TR', 'Trainee'), ('JR', 'Junior'), ('SR', 'Senior'), ('CEO', 'CEO')], default='TR', max_length=3)),
            ],
        ),
    ]
