# Generated by Django 5.2.4 on 2025-09-13 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_delete_employee_remove_article_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='category_id',
        ),
    ]
