# Generated by Django 5.2.4 on 2025-09-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_rename_category_id_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name='content')),
            ],
        ),
    ]
