# Generated by Django 5.2.4 on 2025-09-17 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_articlecomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleComment',
        ),
    ]
